server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1
  postgres:
    addr: "123.249.70.215:5432"
    user: "postgres"
    pwd: "123456"
    db: "postgres"
    schema: "public"

  redis:
    addr: 123.249.70.215:6379
    read_timeout: 1
    write_timeout: 1
